language: php

php:
  - 5.6
  - hhvm
  - nightly

matrix:
    allow_failures:
        - php: nightly
        - php: hhvm

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit